import { test, expect } from '@playwright/test';
import config from '../../Config/config';

test('Customer CheckOut', async ({page}) => {
  await page.goto(`${config.baseUrl}`);
  await page.getByLabel('Profile').click();
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByPlaceholder('email@example.com').click();
  await page.getByPlaceholder('email@example.com').fill('rahul@gmail.com');
  await page.getByPlaceholder('email@example.com').press('Tab');
  await page.getByPlaceholder('Password').fill('rahul@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('#main div').filter({ hasText: 'New Products View All New' }).locator('button').nth(2).click();
  await page.locator('#main div').filter({ hasText: 'New Products View All New' }).locator('button').first().click();
  await page.goto(`${config.baseUrl}/checkout/onepage`);
  await page.locator('#billing_address_id_1').nth(1).click();
  await page.getByText('Use same address for shipping?').click();
  await page.locator('#steps-container form div').filter({ hasText: 'Shipping Address kartikey' }).getByRole('button').click();
  await page.getByPlaceholder('Company Name').click();
  await page.getByPlaceholder('Company Name').fill('webkul');
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('webkul');
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('jasdgh');
  await page.getByPlaceholder('email@example.com').click();
  await page.getByPlaceholder('email@example.com').fill('awsdas@jsj.sdf');
  await page.locator('#steps-container form div').filter({ hasText: 'Street Address' }).nth(1).click();
  await page.getByPlaceholder('Street Address').fill('sdfs sdhgd');
  await page.locator('select[name="shipping\\.country"]').selectOption('AW');
  await page.getByPlaceholder('State').click();
  await page.getByPlaceholder('State').fill('sdfsadfs');
  await page.getByPlaceholder('City').click();
  await page.getByPlaceholder('City').fill('sdfsadfwe');
  await page.getByPlaceholder('Zip/Postcode').click();
  await page.getByPlaceholder('Zip/Postcode').fill('fqwe');
  await page.getByPlaceholder('Telephone').click();
  await page.getByPlaceholder('Telephone').fill('31452345345');
  await page.locator('#save_address').nth(1).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByPlaceholder('Zip/Postcode').click();
  await page.getByPlaceholder('Zip/Postcode').click();
  await page.getByPlaceholder('Zip/Postcode').fill('123214');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('kartikey dubey (webkul) 123ghds, noida, UP, IN,').nth(1).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('label').filter({ hasText: '$20.00Flat Rate - Flat Rate' }).click();
  await page.locator('label').filter({ hasText: 'Cash On DeliveryCash On' }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
});

test('Guest CheckOut', async ({page}) => {
  await page.goto(`${config.baseUrl}`);
  await page.locator('#main div').filter({ hasText: 'New Products View All New' }).locator('button').first().click();
  await page.locator('#main div').filter({ hasText: 'New Products View All New' }).locator('button').nth(1).click();
  await page.locator('#main div').filter({ hasText: 'New Products View All New' }).locator('button').nth(2).click();
  await page.goto(`${config.baseUrl}/checkout/onepage`);
  await page.getByPlaceholder('Company Name').click();
  await page.getByPlaceholder('Company Name').fill('WEBKUL');
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('ASHGDAS');
  await page.getByPlaceholder('First Name').press('Tab');
  await page.getByPlaceholder('Last Name').fill('JASGDSH');
  await page.getByPlaceholder('Last Name').press('Tab');
  await page.getByRole('textbox', { name: 'email@example.com' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('ashdghsd@hjdg.sad');
  await page.getByRole('textbox', { name: 'email@example.com' }).press('Tab');
  await page.getByPlaceholder('Street Address').fill('sdhgfs2367');
  await page.getByPlaceholder('Street Address').press('Tab');
  await page.locator('select[name="billing\\.country"]').selectOption('AI');
  await page.getByPlaceholder('State').click();
  await page.getByPlaceholder('State').fill('sfsyftg');
  await page.getByPlaceholder('City').click();
  await page.getByPlaceholder('City').fill('dgwuyeg');
  await page.getByPlaceholder('Zip/Postcode').click();
  await page.getByPlaceholder('Zip/Postcode').fill('djsbfuweh');
  await page.getByPlaceholder('Telephone').click();
  await page.getByPlaceholder('Telephone').fill('9023723564');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByPlaceholder('Zip/Postcode').click();
  await page.getByPlaceholder('Zip/Postcode').fill('2673854');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('label').filter({ hasText: '$30.00Flat Rate - Flat Rate' }).click();
  await page.locator('label').filter({ hasText: 'Cash On DeliveryCash On' }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
});
