import { test, expect } from '@playwright/test';
import config from '../../Config/config';

test('Create Orders', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.getByRole('button', { name: 'Create Order' }).click();
    await page.getByPlaceholder('Search by email or name').click();
    await page.getByPlaceholder('Search by email or name').fill('Webkul');
    await page.getByPlaceholder('Search by email or name').press('Enter');
    await page.getByPlaceholder('Search by email or name').press('Enter');
    await page.getByRole('button', { name: 'Create Customer' }).click();
    await page.getByPlaceholder('First Name').click();
    await page.getByPlaceholder('First Name').fill('kartikey');
    await page.getByPlaceholder('Last Name').click();
    await page.getByPlaceholder('Last Name').fill('dubey');
    await page.getByPlaceholder('email@example.com').click();
    await page.getByPlaceholder('email@example.com').fill('rte21@gmail.com');
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('09812878623');
    await page.getByPlaceholder('Date of Birth').click();
    await page.getByLabel('December 6,').click();
    await page.getByPlaceholder('Date of Birth').fill('2024-12-06');
    await page.locator('#gender').selectOption('Female');
    await page.locator('#customerGroup').selectOption('3');
    await page.getByRole('button', { name: 'Save customer' }).click();
    await page.getByRole('button', { name: 'Add Product' }).click();
    await page.getByPlaceholder('Search by name').click();
    await page.getByPlaceholder('Search by name').fill('arct');
    await page.locator('input:nth-child(3)').first().click();
    await page.locator('input:nth-child(3)').first().fill('13');
    await page.locator('form > .grid > .cursor-pointer').first().click();
    await page.getByText('+').click();
    await page.getByText('-', { exact: true }).click();
    await page.getByText('Add Address').click();
    await page.getByPlaceholder('Company Name').click();
    await page.getByPlaceholder('Company Name').fill('webkul');
    await page.getByPlaceholder('Vat ID').click();
    await page.getByPlaceholder('First Name').click();
    await page.getByPlaceholder('First Name').fill('kartikeydubey');
    await page.getByPlaceholder('Last Name').click();
    await page.getByPlaceholder('Last Name').fill('dubey');
    await page.getByPlaceholder('email@example.com').click();
    await page.getByPlaceholder('email@example.com').fill('wey@dg.sdd');
    await page.getByPlaceholder('Street Address').click();
    await page.getByPlaceholder('Street Address').fill('hsdguywe');
    await page.locator('select[name="billing\\.country"]').selectOption('BS');
    await page.locator('select[name="billing\\.country"]').selectOption('WF');
    await page.getByPlaceholder('State').click();
    await page.getByPlaceholder('State').fill('dwedwd');
    await page.getByPlaceholder('City').click();
    await page.getByPlaceholder('City').fill('dewdw');
    await page.getByPlaceholder('Zip/Postcode').click();
    await page.getByPlaceholder('Zip/Postcode').fill('2312');
    await page.getByPlaceholder('Telephone').click();
    await page.getByPlaceholder('Telephone').fill('98765432');
    await page.getByPlaceholder('Telephone').press('Enter');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByText('Use same address for shipping?').click();
    await page.locator('#address-step-container div').filter({ hasText: 'Shipping Address Add Address' }).nth(2).click();
    await page.getByText('Add Address').click();
    await page.getByPlaceholder('Company Name').click();
    await page.getByPlaceholder('Company Name').fill('sdsad');
    await page.getByPlaceholder('First Name').click();
    await page.getByPlaceholder('First Name').fill('adasdasa');
    await page.getByPlaceholder('Last Name').click();
    await page.getByPlaceholder('Last Name').dblclick();
    await page.getByPlaceholder('Last Name').fill('adsdasda');
    await page.getByPlaceholder('email@example.com').click();
    await page.getByPlaceholder('email@example.com').fill('dasd@dwew.fgh');
    await page.getByPlaceholder('Street Address').click();
    await page.getByPlaceholder('Street Address').fill('qwerwe');
    await page.locator('select[name="shipping\\.country"]').selectOption('AC');
    await page.getByPlaceholder('State').click();
    await page.getByPlaceholder('State').fill('wewqe');
    await page.getByPlaceholder('City').click();
    await page.getByPlaceholder('City').fill('qweqw3e1');
    await page.getByPlaceholder('Zip/Postcode').click();
    await page.getByPlaceholder('Zip/Postcode').fill('23123');
    await page.getByPlaceholder('Telephone').click();
    await page.getByPlaceholder('Telephone').fill('21111111143');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('button', { name: 'Proceed' }).click();
    await page.locator('div').filter({ hasText: /^Free Shipping$/ }).getByRole('paragraph').click();
    await page.getByRole('button', { name: 'Place Order' }).click();
});

test('Comment on Order', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('.row > div:nth-child(4) > a').first().click();
    await page.getByPlaceholder('Write your comment').click();
    await page.getByPlaceholder('Write your comment').fill('asdasd sdcsda');
    await page.getByRole('button', { name: '' }).click();
    await page.getByLabel('Submit Comment').click();
});

test('Cancel Order', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('.row > div:nth-child(4) > a').first().click();
    await page.locator('.icon-cancel').click();
    await page.getByRole('button', { name: 'Agree', exact: true }).click();
});

test('Reorder', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('.row > div:nth-child(4) > a').first().click();
    await page.getByRole('link', { name: ' Reorder' }).click();
});

test('Create Invoice', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('div:nth-child(7) > div:nth-child(4) > a').click();
    await page.getByText('Invoice', { exact: true }).click();
    await page.locator('#can_create_transaction').nth(1).click();
    await page.getByRole('button', { name: 'Create Invoice' }).click();
});

test('Create Shipment', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('div:nth-child(7) > div:nth-child(4) > a').click();
    await page.getByText('Ship', { exact: true }).click();
    await page.getByPlaceholder('Tracking Number').click();
    await page.getByPlaceholder('Tracking Number').fill('23');
    await page.getByPlaceholder('Carrier Name').click();
    await page.getByPlaceholder('Carrier Name').fill('dsfsdf');
    await page.locator('[id="shipment\\[source\\]"]').selectOption('1');
    await page.getByRole('button', { name: 'Create Shipment' }).click();
});

test('Create Refund', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.locator('div:nth-child(7) > div:nth-child(4) > a').click();
    await page.locator('.icon-cancel').click();
    await page.getByRole('button', { name: 'Refund' }).click();
});

test('Mail Invoice', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.getByRole('link', { name: 'Invoices' }).click();
    await page.locator('div').filter({ hasText: /^42\$55\.00Paid2024-12-18 15:22:57$/ }).locator('span').click();
    await page.getByRole('button', { name: ' Send Duplicate Invoice' }).click();
    await page.locator('#email').click();
    await page.locator('#email').fill('rahul@gmail.com');
    await page.getByRole('button', { name: 'Send', exact: true }).click();
});

test('Print Invoice', async ({page}) => {
    await page.goto(`${config.baseUrl}/admin/login`);
    await page.getByPlaceholder('Email Address').click();
    await page.getByPlaceholder('Email Address').fill('admin@example.com');
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('admin123');
    await page.getByLabel('Sign In').click();
    await page.getByRole('link', { name: ' Sales' }).click();
    await page.getByRole('link', { name: 'Invoices' }).click();
    await page.locator('div').filter({ hasText: /^42\$55\.00Paid2024-12-18 15:22:57$/ }).locator('span').click();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: ' Print' }).click();
    const download = await downloadPromise;
});
