name: Bagisto Playwright Tests

on:
  push:
    branches: [v2.2.2]
  pull_request:
    branches: [v2.2.2]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: webkul
          MYSQL_DATABASE: bagisto-test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -pwebkul"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client netcat-openbsd net-tools

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL..."
          max_attempts=30
          attempt=0
          until mysqladmin ping -h 127.0.0.1 -uroot -pwebkul --silent; do
            if [ $attempt -ge $max_attempts ]; then
              echo "MySQL failed to start in time."
              exit 1
            fi
            echo "Waiting for MySQL... (attempt $((attempt+1))/$max_attempts)"
            sleep 2
            ((attempt++))
          done


      - name: Configure MySQL user privileges
        run: |
          mysql -h 127.0.0.1 -uroot -pwebkul -e "
            CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'webkul';
            GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
            FLUSH PRIVILEGES;
          "

      - name: Set up application environment
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=bagisto-test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=webkul/' .env

      - name: Install PHP and dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, gd, pdo_mysql, mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install

      - name: Test MySQL Connectivity
        run: |
          echo "Testing MySQL connection..."
          php -r "
            try {
                \$pdo = new PDO('mysql:host=127.0.0.1;dbname=bagisto-test', 'root', 'webkul');
                echo 'Connected to MySQL successfully!';
            } catch (PDOException \$e) {
                echo 'Connection failed: ' . \$e->getMessage();
                exit(1);
            }
          "

      - name: Run Laravel migrations
        run: |
          php artisan key:generate
          php artisan migrate --seed
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: bagisto-test
          DB_USERNAME: root
          DB_PASSWORD: webkul

      - name: Start Laravel server
        run: nohup php artisan serve --host=0.0.0.0 --port=8000 > /dev/null 2>&1 &

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Download and Set Up ngrok
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok.zip -d $HOME/.local/bin/
          chmod +x $HOME/.local/bin/ngrok

      - name: Authenticate ngrok
        run: $HOME/.local/bin/ngrok authtoken 2lMZ2Y73YCgcQCeVWbS1HxGt0y2_7ZRqWcHBYAQ6v3mTCV1fo

      - name: Expose Playwright UI with ngrok
        run: |
          nohup xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test --ui &
          $HOME/.local/bin/ngrok http 9323 > ngrok.log &
          sleep 5
          cat ngrok.log | grep https

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
