name: Bagisto Playwright Tests

on:
  push:
    branches: [ v2.2.2 ]
  pull_request:
    branches: [ v2.2.2 ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, gd, pdo_sqlite
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install
          cp .env.example .env
          touch database/database.sqlite
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=/' .env
          sed -i 's/DB_DATABASE=bagisto-test/DB_DATABASE=database\/database.sqlite/' .env

      - name: Set up environment
        run: |
          php artisan key:generate
          php artisan migrate --seed
        env:
          APP_NAME: Bagisto
          APP_ENV: local
          APP_DEBUG: true
          APP_URL: http://localhost:8000
          APP_ADMIN_URL: admin
          APP_TIMEZONE: Asia/Kolkata
          APP_LOCALE: en
          APP_CURRENCY: USD
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Start Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        env:
          APP_ENV: local
          APP_DEBUG: true
          APP_URL: http://localhost:8000

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: 'http://localhost:8000'
        run: npx playwright test --workers=1

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Show Playwright test report
        run: npx playwright show-report
