name: Bagisto Playwright Tests

on:
  push:
    branches: [ v2.2.2 ]
  pull_request:
    branches: [ v2.2.2 ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bagisto-test
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=10s --health-retries=3

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, gd, pdo_mysql
          tools: composer

      # Step 3: Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: composer install

      # Step 5: Wait for MySQL to be ready using wait-for-it.sh
      - name: Download wait-for-it
        run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh

      - name: Wait for MySQL to be ready
        run: ./wait-for-it.sh mysql:3306 --timeout=180 --strict -- echo "MySQL is up"

      # Step 6: Configure Bagisto
      - name: Set up environment
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env
          php artisan key:generate
          php artisan migrate --seed
        env:
          APP_NAME: Bagisto
          APP_ENV: local
          APP_DEBUG: true
          APP_URL: http://localhost:8000
          APP_ADMIN_URL: admin
          APP_TIMEZONE: Asia/Kolkata
          APP_LOCALE: en
          APP_CURRENCY: USD
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: bagisto-test
          DB_USERNAME: root
          DB_PASSWORD: webkul

      # Step 7: Start Laravel server
      - name: Start Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        env:
          APP_ENV: local
          APP_DEBUG: true
          APP_URL: http://localhost:8000

      # Step 8: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 9: Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Step 10: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 11: Run Playwright tests
      - name: Run Playwright tests
        env:
          BASE_URL: 'http://localhost:8000'
        run: npx playwright test --workers=1

      # Step 12: Upload Playwright test report
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Optional: Show the Playwright test report
      - name: Show Playwright test report
        run: npx playwright show-report
