name: Bagisto Playwright Tests

on:
  push:
    branches: [v2.2.2]
  pull_request:
    branches: [v2.2.2]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: webkul
          MYSQL_DATABASE: bagisto-test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -pwebkul"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client netcat-openbsd net-tools

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL..."
          max_attempts=30
          attempt=0
          until mysqladmin ping -h 127.0.0.1 -uroot -pwebkul --silent; do
            if [ $attempt -ge $max_attempts ]; then
              echo "MySQL failed to start in time."
              exit 1
            fi
            echo "Waiting for MySQL... (attempt $((attempt+1))/$max_attempts)"
            sleep 2
            ((attempt++))
          done

      - name: Configure MySQL user privileges
        run: |
          mysql -h 127.0.0.1 -uroot -pwebkul -e "
            CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'webkul';
            GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
            FLUSH PRIVILEGES;
          "

      - name: Set up application environment
        run: |
          cp .env.example .env
          sed -i 's#DB_HOST=.*#DB_HOST=127.0.0.1#' .env
          sed -i 's#DB_PORT=.*#DB_PORT=3306#' .env
          sed -i 's#DB_DATABASE=.*#DB_DATABASE=bagisto-test#' .env
          sed -i 's#DB_USERNAME=.*#DB_USERNAME=root#' .env
          sed -i 's#DB_PASSWORD=.*#DB_PASSWORD=webkul#' .env
          sed -i 's#APP_DEBUG=.*#APP_DEBUG=false#' .env
          sed -i 's|APP_URL=.*|APP_URL=http://127.0.0.1:8000/|' .env

      - name: Install PHP and dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, gd, pdo_mysql, mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install

      - name: Test MySQL Connectivity
        run: |
          echo "Testing MySQL connection..."
          php -r "
            try {
                \$pdo = new PDO('mysql:host=127.0.0.1;dbname=bagisto-test', 'root', 'webkul');
                echo 'Connected to MySQL successfully!';
            } catch (PDOException \$e) {
                echo 'Connection failed: ' . \$e->getMessage();
                exit(1);
            }
          "

      - name: Install Bagisto
        run: |
          # Run the bagisto:create command to create a new project
          composer create

          # Install Bagisto
          php artisan bagisto:install --no-interaction

      - name: Run Laravel migrations
        run: |
          php artisan key:generate
          php artisan migrate --seed
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: bagisto-test
          DB_USERNAME: root
          DB_PASSWORD: webkul
          APP_DEBUG: false
          APP_URL: http://127.0.0.1:8000

      - name: Seed Product Table
        run: php artisan db:seed --class="Webkul\\Installer\\Database\\Seeders\\ProductTableSeeder"

      - name: Start Laravel server
        run: nohup php artisan serve --host=0.0.0.0 --port=8000 > /dev/null 2>&1 &

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright for Shop tests
        env:
          BASE_URL: 'http://127.0.0.1:8000'
        run: |
          npx playwright test tests/shop --workers=1 --project=chromium --retries=0 --reporter=junit --output=results-shop || echo "Some tests failed, but we continue."

          # Parse the results for Shop tests
          total=$(grep -oP 'tests="(\d+)"' results-shop/results.xml | grep -oP '\d+')
          failures=$(grep -oP 'failures="(\d+)"' results-shop/results.xml | grep -oP '\d+')
          pass=$((total - failures))
          shop_pass_rate=$((100 * pass / total))
          echo "Shop tests pass rate: $shop_pass_rate%"

      - name: Run Playwright for Admin tests
        env:
          BASE_URL: 'http://127.0.0.1:8000'
        run: |
          npx playwright test tests/admin --workers=1 --project=chromium --retries=0 --reporter=junit --output=results-admin || echo "Some tests failed, but we continue."

          # Parse the results for Admin tests
          total=$(grep -oP 'tests="(\d+)"' results-admin/results.xml | grep -oP '\d+')
          failures=$(grep -oP 'failures="(\d+)"' results-admin/results.xml | grep -oP '\d+')
          pass=$((total - failures))
          admin_pass_rate=$((100 * pass / total))
          echo "Admin tests pass rate: $admin_pass_rate%"

      - name: Calculate Total Pass Percentage
        run: |
          # Combine Shop and Admin results
          shop_total=$(grep -oP 'tests="(\d+)"' results-shop/results.xml | grep -oP '\d+')
          shop_failures=$(grep -oP 'failures="(\d+)"' results-shop/results.xml | grep -oP '\d+')
          shop_pass=$((shop_total - shop_failures))

          admin_total=$(grep -oP 'tests="(\d+)"' results-admin/results.xml | grep -oP '\d+')
          admin_failures=$(grep -oP 'failures="(\d+)"' results-admin/results.xml | grep -oP '\d+')
          admin_pass=$((admin_total - admin_failures))

          total=$((shop_total + admin_total))
          passed=$((shop_pass + admin_pass))
          pass_rate=$((100 * passed / total))

          echo "Total Pass Rate: $pass_rate%"

          # Exit if the pass rate is below 90%
          if (( pass_rate < 90 )); then
            echo "Pass rate is below 90%. Failing the workflow."
            exit 1
          else
            echo "Pass rate is above 90%. Continuing."
          fi
          
      - name: Upload Playwright Videos of tests
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-videos
          path: videos/
          retention-days: 30

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
